NsbDemo.UI - Copy/Controllers/ApplicationController.cs
using NsbDemo.Core.Entities;
using NsbDemo.Contracts.Commands;
using Raven.Client;
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using NsbDemo.Contracts.Messages;

namespace NsbDemo.UI.Controllers
{
    public class ApplicationController : Controller
    {
        readonly IDocumentSession session;

        public ApplicationController(IDocumentSession session)
        {
            this.session = session;
        }

        #region Get
        public ActionResult Index()
        {
            return View(Application.Create("Mr", "Kelly", "Cliffe", "RC454", "Here", "There", "8080", "Chch", "...@gmail.com"));
        }

        public ActionResult ImagesPending()
        {
            var appsPending = session.Query<Application>().Where(a => a.Status == ApplicationStatus.PendingImageVerification);

            return View(appsPending);
        }

        [HttpGet]
        public ActionResult ApplicationsExpired()
        {
            var appsExpired = session.Query<Application>().Where(a => a.Status == ApplicationStatus.Expired);

            return View(appsExpired);
        }
        #endregion

        #region Post
        [HttpPost]
        public JsonResult Create(string title,
            string firstName,
            string lastName,
            string refereeCardReference,
            string addressLine1,
            string addressLine2,
            string postCode,
            string city,
            string emailAddress,
            DateTime? dateOfBirth)
        {
            // Send() does not require explicit knowledge of the destination queue. This is defined via routing configuration.
            Helpers.GetBus()
                .Send(new ReceiveApplicationCommand(title, firstName, lastName, refereeCardReference, addressLine1, addressLine2,
                    postCode, city, emailAddress));

            return Json(new { Msg = "Ok" });
        }

        // Yep - it should be post since we'll be altering state. Demo disclaimer...
        [HttpGet]
        public void ImageProcessed(string applicationId)
        {
            Helpers.GetBus()
                .Send(new ApplicationImageProcessedCommand(applicationId));
        }

        [HttpGet]
        public void Test()
        {
            Helpers.GetBus().Send(new TestMessage());
        }

        #endregion
    }
}

NsbDemo.UI - Copy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="bikepartsnz">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("Home", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Create", "Index", "Application")</li>
                        <li>@Html.ActionLink("Images Pending", "ImagesPending", "Application")</li>
                        <li>@Html.ActionLink("Apps Expired", "ApplicationsExpired", "Application")</li>
                        <li>@Html.ActionLink("Test", "Test", "Application")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @*<script type="text/javascript" src="~/scripts/angular.js"></script>
    <script type="text/javascript" src="~/scripts/controllers/productListController.js"></script>
    <script src="/scripts/controllers/app.js"></script>
    <script src="/scripts/services/products.js"></script>
    <script src="/scripts/angular-resource.js"></script>*@
    <script src="/scripts/form2js.js"></script>
    <script src="/scripts/jQuery.toObject.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>